Notification Feature
dsc-iem/blog pull request #45
Opened 2020-12-13 11:13 UTC by Riken-Shah

Added notification workflow.

Changes I have made:
- Added the Alert Model
- Integrated Alert Model with the existing API endpoint to create an alert
- Created a new API endpoint to send new alerts
- Created a new API endpoint to mark alerts seen
- Created a hamburger menu for navbar (for smaller width devices)
- Add Notification UI in the navbar

2020-12-13 17:11 UTC, asrient commented on dscblog/paths.py
> +                Alert.create_alert(ref_user=request.user, type=Alert.COMMENT_REPLY if ref else Alert.COMMENT, blog=b)
The user getting the alert for COMMENT_REPLY should be the ref comment's user (the person who the user replied to) not the blog author. This is causing some bugs like if i comment on someone's blog and the author replies me back im not getting the alert (as im not the author)

2020-12-14 04:18 UTC, asrient requested changes
Hi!
I have requested some changes, pls update ur PR accordingly.

2020-12-14 04:18 UTC, asrient commented on dscblog/pages/header.html
> +            <a class="hd_opt btn btn-bordered" href="#" id="notification-bell">
remove the `href="#"` its interfering with navigation history in an unwanted way

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +    transition: transform 1s linear;
make it 0.2s

2020-12-14 04:18 UTC, asrient commented on dscblog/paths.py
> +                Alert.create_alert(ref_user=request.user, type=Alert.COMMENT_REPLY if ref else Alert.COMMENT, blog=b)
The user getting the alert for COMMENT_REPLY should be the ref comment's user (the person who the user replied to) not the blog author. This is causing some bugs like if i comment on someone's blog and the author replies me back im not getting the alert (as im not the author)

2020-12-14 04:18 UTC, asrient commented on dscblog/pages/header.html
> +        fetchNewAlerts();
Call `fetchNewAlerts()` after `setAlertsSeen()` is done completely (use a callback). Cuz these are async functions, if `fetchNewAlerts()` gets done before `setAlertsSeen()` finishes, the notif bubble will still remain.

2020-12-14 04:18 UTC, asrient commented on dscblog/models.py
> +                    {'alert': f'<a href="/@{alert.ref_user.username}">{alert.ref_user}</a> posted a new blog on <a href="{alert.blog.get_url()}">{alert.blog.title}</a>.', 'timestamp': alert.timestamp
make it `user1 posted a new blog "[blog title]"`

2020-12-14 04:18 UTC, asrient commented on dscblog/models.py
> +                msg += f" on <a href={info[key]['url']}>{info[key]['name']}</a> blog"
make it `on "[blog title]"`

2020-12-14 04:18 UTC, asrient commented on dscblog/models.py
> +        (REACTION, 'Reaction'),
use small case for the description eg: `(COMMENT, 'comment')`

2020-12-14 04:18 UTC, asrient commented on dscblog/models.py
> +        return type
make it work for plural terms as well, like `comments`, `reactions`

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +  overflow-y: scroll;
make it `auto`

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +
add: 
border-radius: 0.2rem;
padding: 0.5rem 0.7rem;

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +  box-shadow: 0 6px 12px rgba(0,0,0,.175);
for dark mode:
`box-shadow: 4px 5px 0px rgb(158 158 158);`
for light mode, change the shadow color to dark (more consistent with the theme)

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +  background: rgba(219, 219, 219, 1);
rgb(244 244 244)

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +  background: rgb(55, 55, 55);
rgb(38 38 38)

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +  border: 1px solid rgba(0,0,0,.15);
For dark mode:
`border: 1px solid rgb(255 255 255 / 95%);`
For light mode:
`border: 1px solid rgb(0 0 0 / 95%);`

2020-12-14 04:18 UTC, asrient commented on dscblog/pages/header.html
> +            $('#new-alerts').append('<div class="alert">Sorry, No new alerts found.</div>');
instead of this, just hide the new alerts section

2020-12-14 04:18 UTC, asrient commented on dscblog/pages/header.html
> +            $('#old-alerts').append('<div class="alert">Sorry, No old alerts found.</div>');
instead, hide the old alerts section

2020-12-14 04:18 UTC, asrient commented on dscblog/models.py
> +                        msg += 'and '
add the word `new` to msg, like `You have 1 new comment on...`

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +  display: none;
make the scrollbar hide only on mobile, on desktop use a custom sleek scrollbar

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +  border-bottom: solid .5px #959090;
make the border color lighter..
for dark mode: #474747
light mode: #c8c8c8

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +.notification-wrapper .notification .alerts-wrapper .alert{
remove the border-bottom for the last item:
```css
.notification-wrapper .notification .alerts-wrapper .alert:last-child {
    border-bottom: none;
}
```

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +  font-size: .9rem;
font-size: .85rem;
color: var(--grey); //For older alerts
color: rgb(186 186 186); //For new alerts (dark m)
color: rgb(59 59 59); //For new alerts (light m)

2020-12-14 04:18 UTC, asrient commented on dscblog/static/styles/header.css
> +
Add:
```css
.notification-wrapper .notification .alerts-wrapper .alert a {
    color: var(--secondary);
    font-weight: 600;
}
```
for older alerts, change the color to less contrasting.

2020-12-14 04:18 UTC, asrient commented on dscblog/models.py
> +                grouped_alerts.append({'alert': f'<a href="/@{alert.ref_user.username}">{alert.ref_user}</a> started '
use the actual `name` of the user instead of their `username` if avaiable

2020-12-14 04:18 UTC, asrient commented on dscblog/pages/header.html
> +                    <span class="type">New Alerts</span>
rename it `New`

2020-12-14 04:18 UTC, asrient commented on dscblog/pages/header.html
> +                    <span class="type">Old Alerts</span>
rename it `Earlier`

2020-12-14 04:20 UTC, Riken-Shah commented on dscblog/models.py
> +        (REACTION, 'Reaction'),
Ok

2020-12-14 06:40 UTC, Riken-Shah commented on dscblog/pages/header.html
> +            $('#new-alerts').append('<div class="alert">Sorry, No new alerts found.</div>');
What would happen If the user has no alerts?

2020-12-14 09:21 UTC, asrient commented on dscblog/pages/header.html
> +            $('#new-alerts').append('<div class="alert">Sorry, No new alerts found.</div>');
Put a text positioned centre of the modal saying something like "No new notifications" or something cool.

2020-12-16 17:55 UTC, asrient approved these changes

2020-12-16 17:56 UTC, merged